=== eposlabs/epos/apps/web/public/schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$id": "https://epos.dev/schema.json",
  "title": "epos.json",

  "type": "object",
  "properties": {
    "$schema": { "type": "string" },
    "name": { "$ref": "#/$defs/Name" },
    "slug": { "$ref": "#/$defs/Slug" },
    "version": { "$ref": "#/$defs/Version" },
    "description": { "$ref": "#/$defs/Description" },
    "icon": { "$ref": "#/$defs/Icon" },
    "action": { "$ref": "#/$defs/Action" },
    "popup": { "$ref": "#/$defs/Popup" },
    "options": { "$ref": "#/$defs/Options" },
    "assets": { "$ref": "#/$defs/Assets" },
    "targets": { "$ref": "#/$defs/Targets" },
    "matches": { "$ref": "#/$defs/Matches" },
    "load": { "$ref": "#/$defs/Resources" },
    "permissions": { "$ref": "#/$defs/Permissions" },
    "optionalPermissions": { "$ref": "#/$defs/OptionalPermissions" },
    "hostPermissions": { "$ref": "#/$defs/HostPermissions" },
    "optionalHostPermissions": { "$ref": "#/$defs/HostPermissions" },
    "manifest": { "$ref": "#/$defs/Manifest" }
  },
  "required": ["name"],
  "additionalProperties": false,

  "$defs": {
    "Name": {
      "type": "string",
      "minLength": 2,
      "maxLength": 45
    },

    "Slug": {
      "type": "string",
      "minLength": 2,
      "maxLength": 45,
      "pattern": "^[a-z][a-z0-9-]*[a-z0-9]$"
    },

    "Version": {
      "type": "string",
      "pattern": "^(?:\\d{1,5}\\.){0,3}\\d{1,5}$"
    },

    "Description": {
      "type": "string",
      "maxLength": 132
    },

    "Icon": {
      "type": "string"
    },

    "Action": {
      "oneOf": [{ "type": "null" }, { "type": "string" }, { "type": "boolean" }]
    },

    "Popup": {
      "type": "object",
      "properties": {
        "width": { "type": "number", "minimum": 150, "maximum": 800, "default": 380 },
        "height": { "type": "number", "minimum": 150, "maximum": 572, "default": 572 }
      },
      "additionalProperties": false
    },

    "Options": {
      "type": "object",
      "properties": {
        "preloadAssets": { "type": "boolean", "default": true },
        "allowProjectsApi": { "type": "boolean", "default": false },
        "allowMissingModels": { "type": "boolean", "default": false }
      },
      "additionalProperties": false
    },

    "Assets": {
      "type": "array",
      "items": { "type": "string" }
    },

    "Targets": {
      "type": "array",
      "items": { "$ref": "#/$defs/Target" }
    },

    "Target": {
      "type": "object",
      "properties": {
        "matches": { "$ref": "#/$defs/Matches" },
        "load": { "$ref": "#/$defs/Resources" }
      },
      "additionalProperties": false
    },

    "Matches": {
      "oneOf": [{ "$ref": "#/$defs/Match" }, { "type": "array", "items": { "$ref": "#/$defs/Match" } }]
    },

    "Match": {
      "type": "string"
    },

    "Resources": {
      "oneOf": [{ "$ref": "#/$defs/Resource" }, { "type": "array", "items": { "$ref": "#/$defs/Resource" } }]
    },

    "Resource": {
      "type": "string",
      "pattern": "^.*\\.(css|js|[^.]+)$"
    },

    "Permissions": {
      "type": "array",
      "items": { "$ref": "#/$defs/Permission" }
    },

    "OptionalPermissions": {
      "type": "array",
      "items": { "$ref": "#/$defs/OptionalPermission" }
    },

    "Permission": {
      "type": "string",
      "enum": [
        "alarms",
        "background",
        "browsingData",
        "contextMenus",
        "cookies",
        "declarativeNetRequest",
        "downloads.ui",
        "downloads",
        "notifications",
        "offscreen",
        "scripting",
        "sidePanel",
        "storage",
        "tabs",
        "unlimitedStorage",
        "webNavigation"
      ]
    },

    "OptionalPermission": {
      "type": "string",
      "enum": [
        "alarms",
        "background",
        "browsingData",
        "contextMenus",
        "cookies",
        "downloads.ui",
        "downloads",
        "notifications",
        "offscreen",
        "scripting",
        "sidePanel",
        "storage",
        "tabs",
        "webNavigation"
      ]
    },

    "HostPermissions": {
      "type": "array",
      "items": { "$ref": "#/$defs/HostPermission" }
    },

    "HostPermission": {
      "type": "string"
    },

    "Manifest": {
      "type": "object"
    }
  }
}

=== eposlabs/epos/apps/dashboard-ext/epos.json
{
  "$schema": "https://epos.dev/schema.json",
  "name": "[epos]",
  "slug": "dashboard",
  "version": "1.10",
  "description": "Web Extension Engine.",
  "options": {
    "allowProjectsApi": true,
    "allowMissingModels": true
  },
  "permissions": [
    "background",
    "browsingData",
    "contextMenus",
    "cookies",
    "downloads.ui",
    "downloads",
    "notifications",
    "sidePanel",
    "storage"
  ],
  "hostPermissions": ["<allUrls>"],
  "targets": [
    {
      "matches": "https://app.epos.dev/*",
      "load": ["public/fonts.css", "dist/gl.css", "dist/gl.js"]
    }
  ],
  "assets": [
    "public/icon.svg",
    "public/icon.png",
    "templates/vite/public/epos.svg",
    "templates/vite/src/background.ts",
    "templates/vite/src/main.css",
    "templates/vite/src/main.tsx",
    "templates/vite/gitignore",
    "templates/vite/epos.json",
    "templates/vite/package.json",
    "templates/vite/tsconfig.json",
    "templates/vite/vite.config.ts"
  ]
}

=== eposlabs/epos/apps/shell/epos.json
{
  "$schema": "https://epos.dev/schema.json",
  "name": "[epos]",
  "slug": "shell",
  "version": "1.8",
  "description": "Web Extension Engine",
  "options": { "allowProjectsApi": true, "allowMissingModels": true },

  "assets": ["dist/icon.svg", "dist/icon.png"],
  "matches": ["https://app.epos.dev/*", "https://epos.dev/@learn"],
  "load": ["dist/fonts.css", "dist/gl.css", "dist/gl.js"],

  "hostPermissions": ["<allUrls>"],
  "permissions": [
    "background",
    "browsingData",
    "contextMenus",
    "cookies",
    "downloads",
    "notifications",
    "sidePanel",
    "storage"
  ]
}

=== eposlabs/epos/playground/bridge/epos.json
{
  "$schema": "https://epos.dev/schema.json",
  "name": "UnitBridge",
  "slug": "bridge-6",
  "assets": ["./public/logo.svg"],
  "targets": [
    {
      "matches": ["<popup>", "https://epos.dev/@bridge"],
      "load": ["./dist/app.js", "./dist/app.css"]
    },
    {
      "matches": "<background>",
      "load": ["./dist/background.js"]
    }
  ]
}
