=== eposlabs/epos/web/public/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://epos.dev/schema.json",
  "title": "epos.json",

  "type": "object",
  "properties": {
    "$schema": { "type": "string" },
    "name": { "$ref": "#/definitions/Name" },
    "icon": { "$ref": "#/definitions/Icon" },
    "title": { "$ref": "#/definitions/Title" },
    "description": { "$ref": "#/definitions/Description" },
    "version": { "$ref": "#/definitions/Version" },
    "action": { "$ref": "#/definitions/Action" },
    "popup": { "$ref": "#/definitions/Popup" },
    "assets": { "$ref": "#/definitions/Assets" },
    "targets": { "$ref": "#/definitions/Targets" },
    "matches": { "$ref": "#/definitions/Matches" },
    "load": { "$ref": "#/definitions/Load" },
    "mode": { "$ref": "#/definitions/Mode" },
    "manifest": { "$ref": "#/definitions/Manifest" }
  },
  "required": ["name"],
  "additionalProperties": false,

  "definitions": {
    "Name": {
      "type": "string",
      "minLength": 2,
      "maxLength": 45,
      "pattern": "^[a-z0-9\\-]+$"
    },

    "Icon": {
      "type": "string"
    },

    "Title": {
      "type": "string",
      "maxLength": 45
    },

    "Description": {
      "type": "string",
      "description": "A plain text description of the extension",
      "maxLength": 132
    },

    "Version": {
      "type": "string",
      "pattern": "^(?:\\d{1,5}\\.){0,3}\\d{1,5}$"
    },

    "Action": {
      "oneOf": [{ "type": "null" }, { "type": "string" }, { "type": "boolean" }]
    },

    "Popup": {
      "type": "object",
      "properties": {
        "width": { "type": "number", "minimum": 150, "maximum": 800, "default": 400 },
        "height": { "type": "number", "minimum": 150, "maximum": 600, "default": 600 }
      },
      "additionalProperties": false
    },

    "Assets": {
      "type": "array",
      "items": { "$ref": "#/definitions/Asset" }
    },

    "Asset": {
      "type": "string"
    },

    "Targets": {
      "type": "array",
      "items": { "$ref": "#/definitions/Target" }
    },

    "Target": {
      "type": "object",
      "properties": {
        "matches": { "$ref": "#/definitions/Matches" },
        "load": { "$ref": "#/definitions/Load" },
        "mode": { "$ref": "#/definitions/Mode" }
      },
      "additionalProperties": false
    },

    "Matches": {
      "oneOf": [
        { "$ref": "#/definitions/Pattern" },
        { "type": "array", "items": { "$ref": "#/definitions/Pattern" } }
      ]
    },

    "Pattern": {
      "type": "string"
    },

    "Load": {
      "oneOf": [
        { "$ref": "#/definitions/LoadItem" },
        { "type": "array", "items": { "$ref": "#/definitions/LoadItem" } }
      ]
    },

    "LoadItem": {
      "type": "string",
      "pattern": "^.*\\.(css|js|[^.]+)$"
    },

    "Mode": {
      "type": "string",
      "enum": ["normal", "shadow", "lite"]
    },

    "Manifest": {
      "$ref": "./manifest.schema.json"
    }
  }
}

=== eposlabs/epos/devkit/epos.json
{
  "$schema": "https://epos.dev/schema.json",
  "name": "devkit",
  "title": "[epos] DevKit",
  "assets": [
    "./public/icon.png",
    "./template/epos.json",
    "./template/package.json",
    "./template/tsconfig.json",
    "./template/vite.config.ts",
    "./template/src/app/app.gl.tsx",
    "./template/src/entry/entry.gl.tsx",
    "./template/src/entry/entry.gl.css",
    "./template/src/entry/entry-units.ts"
  ],
  "targets": [
    {
      "matches": ["<hub>"],
      "load": ["./dist/gl.js", "./dist/gl.css"]
    }
  ],

  "manifest": {
    "name": "[epos]",
    "version": "1.0",
    "manifest_version": 3
  }
}

=== eposlabs/epos/packages/epos-devkit/template/epos.json
{
  "$schema": "https://epos.dev/schema.json",
  "name": "epos-template-package",
  "action": "<hub>",
  "targets": [
    {
      "matches": ["<hub>"],
      "load": ["./dist/gl.js", "./dist/gl.css"]
    }
  ],

  "manifest": {
    "name": "Epos Template Package",
    "version": "1.0.0",
    "manifest_version": 3
  }
}

=== eposlabs/epos/apps/devkit/epos.json
{
  "$schema": "https://epos.dev/schema.json?v=1",
  "name": "devkit",
  "title": "[epos]",
  "description": "Epos helps you to develop browser extensions.",
  "version": "1.5",
  "targets": [
    {
      "matches": ["<hub>"],
      "load": ["./dist/gl.js", "./dist/tw.css"]
    },
    {
      "matches": ["https://epos.dev/@learn"],
      "load": ["./dist/ln.js", "./dist/tw.css"]
    }
  ]
}

=== eposlabs/epos/playgrounds/learn/public/epos.json
{
  "$schema": "https://epos.dev/schema.json",
  "name": "learn",
  "title": "[epos] Learn Browser API",
  "action": "<hub>",
  "targets": [
    {
      "matches": ["<hub>", "<popup>", "https://inssist.com/*"],
      "load": ["./fg.js", "./fg.css"],
      "mode": "shadow"
    },
    {
      "matches": "<background>",
      "load": ["./bg.js"]
    }
  ]
}

=== eposlabs/epos/playgrounds/2/epos.json
{
  "$schema": "https://epos.dev/schema.json",
  "name": "epos-template-package-3",
  "action": "<hub>",
  "targets": [
    {
      "matches": ["<hub>", "<popup>"],
      "load": ["./dist/gl.js", "./dist/gl.css"]
    }
  ],

  "manifest": {
    "name": "Epos Template Package",
    "version": "1.0.0",
    "manifest_version": 3
  }
}
